# This file was generated by GoReleaser. DO NOT EDIT.
cask "kpub" do
  name "kpub"
  desc "Telegram chat monitor and ebook pipeline for Kobo"
  homepage "https://github.com/spacesedan/kpub"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kpub"
  depends_on formula: [
      "docker",
    ]

  on_macos do
    on_intel do
      url "https://github.com/spacesedan/kpub/releases/download/v#{version}/kpub_darwin_amd64.tar.gz"
      sha256 "51a3b967c9d3c4d8d469f81621a810b3388c6b09c02e0d2aa0ff0d1121aac2ac"
    end
    on_arm do
      url "https://github.com/spacesedan/kpub/releases/download/v#{version}/kpub_darwin_arm64.tar.gz"
      sha256 "7b0b5086f3fad0a8785a986c8990f64f41169d605b8bb9a3e7b9c2b66a2539db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/spacesedan/kpub/releases/download/v#{version}/kpub_linux_amd64.tar.gz"
      sha256 "1ff6047c31aaf3774bd525872e3462be941bc849c0a1c851c307b2791a12450e"
    end
    on_arm do
      url "https://github.com/spacesedan/kpub/releases/download/v#{version}/kpub_linux_arm64.tar.gz"
      sha256 "7e73b6d65f9114ffdaec6e602dc4967686fbb574f74eb3084af692832108eede"
    end
  end

  # No zap stanza required
end
